import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Crisis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="hero min-h-screen bg-gradient-to-br from-gray-600 to-red-300">
        <div class="hero-overlay bg-opacity-60"></div>
        <div class="hero-content text-center text-neutral-content">
          <div class="max-w-md">
            <h1 class="mb-5 text-5xl font-bold">Crisis</h1>
            <p class="mb-5">
              Free horror RPG game.
              <br />
              Made by tamagoez for hobby.
            </p>
            <div className="flex justify-center space-x-2">
              <Link href="./dl/" passHref>
                <a className="btn btn-secondary hover:animate-pulse">Get App</a>
              </Link>
              <button class="btn btn-secondary hover:animate-pulse">
                Play on WEB
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
